---
title: Dripdotdesign
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
    permalink: "/:name"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/project/:slug"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: projects
  values:
    layout: project
site: Duet Jekyll Theme
url: 
baseurl: 
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
paginate: 6
paginate_path: "/blog/page:num/"
